### ISSUE TITLE
How I can synchronize it

### ISSUE THREAD

**Issue by cha7ta** [avischiffmann/Coronavirus-Dashboard#121]
Hello dear 
thanks for all.
I have a probleme when I use script he shows old numbers not updated stats, so How I can synchronize it?

and thanks

**Comment by cha7ta** [comment]
the problem here
App 336763 output: Fetching data.
App 336763 output: [SYNC] Fetching all BNO data.
App 336763 output: (node:336763) UnhandledPromiseRejectionWarning: TypeError: covid.countries is not a function
App 336763 output:     at Object.exports.fetchData (/home/ncovsyxh/coovid/micro-scrapers/novelcovid.js:24:34)
App 336763 output:     at syncWithAllCountryList (/home/ncovsyxh/coovid/fetchData.js:106:21)
App 336763 output:     at Promise.all.then.values (/home/ncovsyxh/coovid/fetchData.js:153:5)
App 336763 output: (node:336763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
